---
- name: Creando Reglas Audit
  hosts: all
  tasks:
    - name: Creacion de directorio y regla de auditoría
      ansible.builtin.shell: echo "-w /var/log/lastlog -p wa -k logins" >> /home/mrp4in/audit.txt
      args:
        creates: /home/mrp4in/audit.txt
