---
- name: Ejecutar oc login y crear VM en cluster-upi
  hosts: 10.10.107.110
  gather_facts: no
  become: true
  vars:
    ocp_api_url: https://api.ocp.home.local:6443
    ocp_user: kubeadmin
    ocp_password: qPHJe-VcHgk-f8EHR-xdNDh
    oc_path: /usr/local/bin/oc
    # Datos de Registro Red Hat
    rh_user: "daniel.galicia@moxy-it.com.mx"
    rh_password: "8qHLJ:aULWa:Y5d"
    target_ns: "cluster-upi"

  tasks:
    - name: 1. Iniciar sesión en OpenShift
      ansible.builtin.shell: |
        {{ oc_path }} login {{ ocp_api_url }} \
          -u {{ ocp_user }} -p '{{ ocp_password }}' --insecure-skip-tls-verify
      register: oc_login_result

    - name: 2. Crear VM ansible-vm en namespace cluster-upi
      ansible.builtin.shell: |
        cat <<EOF | {{ oc_path }} apply -f -
        apiVersion: kubevirt.io/v1
        kind: VirtualMachine
        metadata:
          name: ansible-vm
          namespace: {{ target_ns }}
        spec:
          runStrategy: Always
          dataVolumeTemplates:
            - metadata:
                name: ansible-vm-disk
              spec:
                sourceRef:
                  kind: DataSource
                  name: rhel8
                  namespace: openshift-virtualization-os-images
                storage:
                  resources:
                    requests:
                      storage: 30Gi
          template:
            metadata:
              labels:
                network.kubevirt.io/headlessService: headless
            spec:
              nodeSelector:
                kubernetes.io/hostname: worker06.ocp.home.local
              domain:
                cpu:
                  cores: 2
                resources:
                  requests:
                    memory: 4Gi
                devices:
                  disks:
                    - disk:
                        bus: virtio
                      name: rootdisk
                    - disk:
                        bus: virtio
                      name: cloudinitdisk
                  interfaces:
                    - masquerade: {}
                      name: default
                    - model: virtio
                      name: nic-plum-yak-11
                      bridge: {}
              networks:
                - name: default
                  pod: {}
                - name: nic-plum-yak-11
                  multus:
                    networkName: vlan115-net
              volumes:
                - dataVolume:
                    name: ansible-vm-disk
                  name: rootdisk
                - cloudInitNoCloud:
                    userData: |
                      #cloud-config
                      user: rhel
                      password: 'c0i7-cwi7-m8u8'
                      chpasswd: { expire: False }
                      runcmd:
                        - nmcli connection add type ethernet con-name vlan115 ifname eth1 ipv4.method static ipv4.addresses 10.10.115.52/24
                        - nmcli connection up vlan115
                        - subscription-manager register --username "{{ rh_user }}" --password "{{ rh_password }}" --auto-attach
                  name: cloudinitdisk
        EOF
      register: vm_creation

    - name: 3. Resultado
      debug:
        msg: "VM 'ansible-vm' creada correctamente en {{ target_ns }}. Registrando con la IP .52"
